### ISSUE TITLE
Cannot Use sphinx-doc code-block directive inside a quiz. 

### ISSUE THREAD

**Issue by aaronjrenfroe** [bonartm/sphinxcontrib-quizdown#3]
Using Myst I would expect a code-block to be rendered within the quizdown render. But it gets rendered as raw text or an styled code block. 

```` {quizdown}

```{code-block}
print("Hello Quizdown")
```

## What does the code do?
> Think about it

 1. [x] prints "Hello Quizdown" to the console
 2. [ ] prints "Goodbye Quizdown" to the console
 3. [ ] prints "Cheers Quizdown" to the console
 4. [ ] prints "Good day Quizedown" to the console
````

I don't think the normal backtics would work as I am using a custom pygments style for a programming language developed inhouse.

**Comment by bonartm** [comment]
Quizdown uses its own markdown renderer (marked.js) and highlight.js (https://highlightjs.org/) for syntax highlighting. So unfortunately custom language styles are not supported.

**Comment by Josh-Hiz** [comment]
> Quizdown uses its own markdown renderer (marked.js) and highlight.js (https://highlightjs.org/) for syntax highlighting. So unfortunately custom language styles are not supported.

So how would you type code blocks? As whenever I try Quizdown simply squishes down and the code block and dosent render fully, as rather it just condenses everything
